api_platform:
    graphql:
        nesting_separator: __
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    formats:
        multipart:
            mime_types: ['multipart/form-data']