#index:
#    path: /
#    controller: App\Controller\DefaultController::index

authentication_token:
    path: /api/login
    methods: ['POST']

api_graphql_entrypoint:
    path: /api/graphql
    controller: api_platform.graphql.action.entrypoint